"""Deterministic 1-2 narrative and remediation mapping.

Report wording must be reproducible and reviewable.  It is intentionally kept
as version-controlled data instead of being generated by an LLM at runtime.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


GUIDELINE_REFERENCE = "ARGUS 웹/API 개발보안 권고 · 1-2 입력값 검증 기준"


@dataclass(frozen=True, slots=True)
class Guidance:
    label: str
    cause: str
    impact: str
    remediation: tuple[str, ...]


_GUIDANCE: dict[str, Guidance] = {
    "xss": Guidance(
        label="스크립트 삽입(XSS)",
        cause="서비스가 사용자 입·출력 값을 서버 측에서 충분히 검증하거나 출력 문맥에 맞게 인코딩하지 않아",
        impact=(
            "악성 스크립트 실행을 통한 타 사용자의 인증정보 탈취, 사용자 행위 위조, "
            "악성 사이트 유도 및 악성 코드 유포"
        ),
        remediation=(
            "모든 입·출력 값에 대한 검증은 스크립트가 아닌 서버 측에서 수행해야 하며, "
            "입·출력 값 필터링 시 위험한 특수문자에 대한 필터링을 설정해야 합니다.",
            "특수문자에 대한 필터링이 불가능한 경우 XSS 키워드에 대해 필터링을 적용해야 "
            "하며, XSS 키워드 필터링 적용 시 대·소문자를 구분하지 않는 비교 함수를 적용해야 합니다.",
            "HTML, JavaScript, URL 등 출력 위치의 문맥에 맞는 인코딩을 적용하고 사용자 입력값을 "
            "innerHTML과 같은 실행 가능한 DOM API에 직접 전달하지 않아야 합니다.",
        ),
    ),
    "command": Guidance(
        label="운영체제 명령어 삽입",
        cause="서비스가 사용자 입력값을 운영체제 명령어와 안전하게 분리하지 않고 처리하여",
        impact="서버 내 중요정보 탈취, 파일 변조, 서비스 중단 및 시스템 권한 획득",
        remediation=(
            "사용자 입력값을 운영체제 명령어 문자열에 직접 결합하지 말고, 검증된 전용 API 또는 "
            "고정된 명령과 인자 목록을 사용해야 합니다.",
            "명령 실행이 불가피한 경우 서버 측 허용 목록으로 입력 형식과 길이를 검증하고 쉘 메타문자를 "
            "차단해야 하며, 실행 계정에는 업무 수행에 필요한 최소 권한만 부여해야 합니다.",
        ),
    ),
    "ldap": Guidance(
        label="LDAP 질의문 삽입",
        cause="서비스가 사용자 입력값을 LDAP 질의 조건과 안전하게 분리하지 않고 처리하여",
        impact="인증 우회, 사용자·조직정보 노출 및 접근통제 우회",
        remediation=(
            "LDAP 질의 조건에 사용자 입력값을 직접 결합하지 말고 안전한 LDAP API와 이스케이프 함수를 사용해야 합니다.",
            "서버 측 허용 목록을 기준으로 입력 형식과 길이를 검증하고 LDAP 특수문자를 적절히 처리해야 합니다.",
        ),
    ),
    "xpath": Guidance(
        label="XPath 질의문 삽입",
        cause="서비스가 사용자 입력값을 XPath 표현식과 안전하게 분리하지 않고 처리하여",
        impact="인증 우회와 XML 기반 중요정보의 비인가 조회·변조",
        remediation=(
            "XPath 표현식에 사용자 입력값을 직접 연결하지 말고 변수 바인딩을 지원하는 안전한 API를 사용해야 합니다.",
            "서버 측 허용 목록으로 입력값을 검증하고 XPath 제어문자와 연산자를 적절히 처리해야 합니다.",
        ),
    ),
    "sql": Guidance(
        label="SQL 질의문 삽입",
        cause="서비스가 사용자 입력값을 서버 측에서 충분히 검증하거나 SQL 질의문과 안전하게 분리하지 않고 처리하여",
        impact="인증 우회, 중요정보 조회·변조·삭제 및 데이터베이스 권한 탈취",
        remediation=(
            "사용자 입력값을 SQL 문자열에 직접 결합하지 말고 Prepared Statement와 바인딩 변수를 사용해야 합니다.",
            "모든 입력값은 서버 측에서 허용 형식과 길이를 검증해야 하며, 데이터베이스 계정에는 업무 수행에 "
            "필요한 최소 권한만 부여해야 합니다.",
            "오류 응답에는 SQL 구문, 테이블명, 데이터베이스 종류 등 내부 구현 정보가 노출되지 않도록 처리해야 합니다.",
        ),
    ),
    "generic": Guidance(
        label="입력값 삽입 공격",
        cause="서비스가 외부 입력값을 서버 측에서 충분히 검증하거나 명령·질의문과 안전하게 분리하지 않고 처리하여",
        impact="서버 측 처리 흐름 변경, 접근통제 우회 및 중요정보 노출·변조",
        remediation=(
            "모든 외부 입력값은 서버 측에서 허용 목록을 기준으로 형식과 길이를 검증해야 합니다.",
            "입력값을 명령문이나 질의문에 직접 결합하지 말고 대상 인터프리터가 제공하는 안전한 바인딩 API를 사용해야 합니다.",
        ),
    ),
}


def classify_injection(evidence: dict[str, Any], message: str = "") -> str:
    haystack = " ".join(
        str(value or "")
        for value in (
            evidence.get("injection_type"),
            evidence.get("classification"),
            evidence.get("verification_type"),
            evidence.get("plugin_id"),
            message,
        )
    ).lower()
    if any(token in haystack for token in ("xss", "script injection", "cross site")):
        return "xss"
    if any(token in haystack for token in ("command", "cmd", "os injection", "shell")):
        return "command"
    if "ldap" in haystack:
        return "ldap"
    if "xpath" in haystack:
        return "xpath"
    if any(token in haystack for token in ("sql", "boolean", "time", "error_pattern", "union")):
        return "sql"
    return "generic"


def guidance_for(kind: str) -> Guidance:
    return _GUIDANCE.get(kind, _GUIDANCE["generic"])


def detection_method_for(kind: str, verification_type: str) -> str:
    classification = verification_type.upper()
    target = guidance_for(kind).label
    if "BOOLEAN" in classification:
        method = (
            "정상 입력과 참·거짓 조건의 공격 payload를 각각 전송하고 HTTP 상태 코드, 응답 본문 및 "
            "응답 크기의 차이가 반복적으로 재현되는지 비교했습니다."
        )
    elif "TIME" in classification:
        method = (
            "정상 요청과 지연 함수를 포함한 공격 payload를 반복 전송하고 두 요청의 처리 시간을 비교하여 "
            "의도한 지연이 일관되게 발생하는지 확인했습니다."
        )
    elif "ERROR" in classification:
        method = (
            "구문 오류를 유발하는 공격 payload를 전송하고 정상 요청과 비교하여 오류 응답, 데이터베이스 식별자 "
            "또는 내부 질의 정보가 노출되는지 확인했습니다."
        )
    elif kind == "xss":
        method = (
            "스크립트 payload를 입력 파라미터에 삽입하고 응답 반사 여부와 브라우저 문맥에서의 실행 여부를 "
            "정상 요청 결과와 비교했습니다."
        )
    else:
        method = (
            "입력 파라미터에 Injection payload를 삽입한 요청을 전송하고 정상 요청과 공격 요청의 HTTP 상태, "
            "응답 본문, 응답 크기 및 처리 시간 차이를 비교했습니다."
        )
    return f"{target} 가능성을 확인하기 위해 {method} 동일 조건의 요청을 반복하여 결과의 재현성도 확인했습니다."
